AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: VF Deployment

Parameters:
  BucketName:
    Type: String

Resources:
  S3:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref BucketName
      PolicyDocument:
        Statement:
          -
            Action: [ "s3:GetObject" ]
            Effect: Allow
            Principal: "*"
            Resource: !Sub "arn:aws:s3:::${BucketName}/*"

  API:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: "test"
  weather:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./functions/index.js
      Description: >-
        Weather
      MemorySize: 512
      Timeout: 10
      Role: 'arn:aws:iam::575473820147:role/service-role/weather-role-1zekfdcw'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /weather2
            Method: ANY
            RestApiId: !Ref API

  DeploymentLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:375983427419:applications/deploy-to-s3
        SemanticVersion: 2.4.2

  SiteSource:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !GetAtt DeploymentLayer.Outputs.Arn
      CodeUri: ./vf-spa/dist/voice
      AutoPublishAlias: live
      Runtime: python3.6 
      Handler: deployer.resource_handler
      Timeout: 600
      Policies:
        - S3FullAccessPolicy:
            BucketName: !Ref S3

  DeploymentResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt SiteSource.Arn
      Version: !Ref "SiteSource.Version"
      TargetBucket: !Ref S3
      Substitutions:
        FilePattern: "main.js"
        Values:
          API_ENDPOINT: !Sub https://${API}.execute-api.${AWS::Region}.amazonaws.com/test/weather2
      Acl: 'public-read'
      CacheControlMaxAge: 600


Outputs:
  DestinationBucket:
    Value: !Ref S3
  DestinationUrl:
    Value: !GetAtt S3.WebsiteURL
  APIServiceToken:
    Value: !GetAtt weather.Arn
  URL:
    Value: !Sub https://${API}.execute-api.${AWS::Region}.amazonaws.com/test/weather2
